version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install bandit trivy
  pre_build:
    commands:
      - echo "Starting build"
  build:
    commands:
      - echo "Running unit tests"
      - pytest -q || true
      - echo "Running Bandit static scan"
      - bandit -r . -f json -o bandit-report.json || true
      - echo "Building docker image"
      - docker build -t sample-app:latest .
      - echo "Scanning image with Trivy"
      - trivy image --quiet --format json -o trivy-report.json sample-app:latest || true

artifacts:
  files:
    - bandit-report.json
    - trivy-report.json
