version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build
  build:
    commands:
      - echo Build started on `date`
      - docker build -t demo-app:latest .
      - echo Build finished
artifacts:
  files:
    - '**/*'
