version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing tools"
      - pip install bandit==1.8.6 pytest
      - echo "Installing Trivy"
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3

  pre_build:
    commands:
      - echo "Starting build"

  build:
    commands:
      - echo "Running unit tests"
      - pytest -q || true
      - echo "Running Bandit static scan"
      - bandit -r . -f json -o bandit-report.json || true
      - echo "Building docker image"
      - docker build -t sample-app:latest .
      - echo "Scanning image with Trivy"
      - trivy image --format json --output trivy-report.json --no-progress sample-app:latest || true

artifacts:
  files:
    - bandit-report.json
    - trivy-report.json
  name: reports/$CODEBUILD_BUILD_NUMBER/
  discard-paths: yes

